### ISSUE TITLE
Level-Design überlegen

### ISSUE THREAD

**Issue by JonasWin** [PierreRolle/Projektseminar-E-Business#19]
Allgemein sollen die nächsten Levels des Spiels gebrainstormt und die ersten Gedanken dazu festgehalten werden. Folgende Anregungen/Ideen könnten eine Rolle spielen:
- Gegner
- Zeitlimit
- bewegbare Steine

**Comment by PierreRolle** [comment]
Die angeforderten Level für Version 1 wurden fertiggestellt.
