### ISSUE TITLE
Teleportpunkte

### ISSUE THREAD

**Issue by PierreRolle** [PierreRolle/Projektseminar-E-Business#27]
- Zweiseitiger Teleporter
- mit in den Item-Array
- bekommt String in dem Array
- Level-DB erweitern
- Level-Klasse um die Property erweitern
- Spieler wird im Item-Array bewegt (Spieler wäre im Gegner-Array)
- wird automatisch teleportiert, sobald er auf diesen Punkt läuft

**Comment by JonasWin** [comment]
Eine zweiseitige Teleportfunktion wurde im Branch "Teleport" umgesetzt. Hierbei wurde das Item-Array benutzt und erweitert. In der Level-Klasse wurde die Funktionalität, des sich teleportierenden Gegners umgesetzt.
Eine Änderung an der Funktionalität würde ich gerne in dem Jour-Fix am 15.12. besprechen, da diese das Level-Design dynamischer machen könnte.

**Comment by JonasWin** [comment]
Die Teleportpunkte wurden wie gewünscht implementiert. Die Änderungen an der Funktionalität wurden am 15.12 besprochen und vom Team abgesegnet.
